{'agent_groups': {'agent0': {'reward_agents': ('agent0',)},
                  'agent1': {'reward_names': (('dist', 'agent1', 'agent0'),)}},
 'components': {'agent0': {'component': 'ant',
                           'pos': (2.0, 0.0, 0),
                           'reward_fns': {'goal': {'indices': (0, 1),
                                                   'offset': 5.0,
                                                   'reward_type': 'root_goal',
                                                   'sdcomp': 'vel',
                                                   'target_goal': (3.0, 0)}}},
                'agent1': {'component': 'ant',
                           'pos': (-2.0, 2.4492935982947064e-16, 0)}},
 'edges': {'agent0__agent1': {'extra_observers': [{'indices': (0, 1),
                                                   'observer_type': 'root_vec'}],
                              'reward_fns': {'dist': {'max_dist': 20,
                                                      'offset': 21,
                                                      'reward_type': 'root_dist'}}}}}